# Generated by Django 5.1.3 on 2024-11-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='timestamps',
            new_name='timestamp',
        ),
    ]
