# Generated by Django 5.1.3 on 2024-11-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='release_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
