# Generated by Django 5.1.3 on 2024-11-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_rating_avg_anime_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
