# Generated by Django 5.1.3 on 2024-12-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_anime_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
