# Generated by Django 4.2.17 on 2024-12-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_alter_anime_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='idx',
            field=models.IntegerField(blank=True, help_text='Position IDs for ML', null=True),
        ),
    ]
