# Generated by Django 4.2.17 on 2024-12-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
